Add: adaptive grid index
htmlacademy-adaptive/1952105-mishka-25 pull request #5
Opened 2022-04-10 07:33 UTC by Mniimaya

2022-04-10 16:38 UTC, summertime-fms requested changes
Прошелся чисто по коду, по внешнему виду проекта отпишу отдельно в тг. Со стилями порядок, все аккуратненько. Но разметка испортилась. По возможности  к таким классам как hidden-tablet и тд. стоит прибегать в крайних случаях, они засоряют разметку и кажется скрывать элемент можно по его обычному классу/селектору.

2022-04-10 16:38 UTC, summertime-fms commented on source/sass/blocks/about.scss
> +  flex-direction: column;
А в этом есть смысл? Ведь элементы по умолчанию располагаются сверху вниз

2022-04-10 16:38 UTC, summertime-fms commented on source/sass/variables.scss
> +$lg-max: 2000px;
Откуда это значение? У нас есть базовая ширина - 320 и 2 брейкпоинта. 768 и 1150.

2022-04-10 16:38 UTC, summertime-fms commented on source/sass/variables.scss
> +$padding--lg: 40px;
Я думаю это можно дропнуть отсюда, т.к. дублирует переменную выше

2022-04-10 16:38 UTC, summertime-fms commented on source/form.html
> +                  <li class="nav__item item-hidden-tablet">
Можно же просто список скрывать на планшете, без добавления этих классов

2022-04-10 16:38 UTC, summertime-fms commented on source/form.html
> +                      <span class="item-hidden-tablet item-hidden-desktop">Поиск по сайту</span>
Тоже не понимаю зачем эти классы. Ты как обычно стилизуешь элемент по классу а на нужных тебе разрешениях задаешь display none.

2022-04-10 16:38 UTC, summertime-fms commented on source/form.html
> +                        <span class="nav-value">пока пуста</span>
Думаю что в этом классе нет необходимости, т.к. это все стилизуется от родителя вместе со словом Корзина

2022-04-10 16:38 UTC, summertime-fms commented on source/form.html
> +          <span class="form__title legend">фио</span>
А почему ты отказалась от семантичного тега legeng?

2022-04-10 16:38 UTC, summertime-fms commented on source/form.html
> +          <label class="form__label legend" for="form-tel">Тел</label>
Я запутался. У тебя выше стоят лейблы текстовым инпутам. Ты им даешь классы form__label-text form__label, а тут ты лейблам даешь целый бэмовский блок legend. Почему legend? Почему блок?

2022-04-10 16:38 UTC, summertime-fms commented on source/form.html
> +          <span class="form__title legend">Доп</span>
А здесь у тебя этот класс уже у спана а не у лейбла

2022-04-10 16:38 UTC, summertime-fms commented on source/sass/blocks/form-order.scss
> +  @include viewport--md {
Дублирование

2022-04-10 16:51 UTC, Mniimaya commented on source/sass/variables.scss
> +$padding--lg: 40px;
там будет 50px, изменила

2022-04-10 16:55 UTC, Mniimaya commented on source/form.html
> +                  <li class="nav__item item-hidden-tablet">
у меня 2 nav__list, один открывается на планшете, а другой открывается на десктопе

2022-04-10 16:55 UTC, Mniimaya commented on source/form.html
> +                      <span class="item-hidden-tablet item-hidden-desktop">Поиск по сайту</span>
этот класс нужен чтобы оставить только иконку, без слова поиск

2022-04-10 16:57 UTC, Mniimaya commented on source/form.html
> +                        <span class="nav-value">пока пуста</span>
ты же сам говорил, что нужно вынести "пока пуста" чтобы значение менялось

2022-04-10 16:58 UTC, Mniimaya commented on source/form.html
> +          <label class="form__label legend" for="form-tel">Тел</label>
это микс для задания параметров шрифта, поменяю

2022-04-11 10:00 UTC, summertime-fms commented on source/form.html
> +                  <li class="nav__item item-hidden-tablet">
ну так задай второму модификатор

2022-04-11 10:41 UTC, summertime-fms commented on source/form.html
> +                      <span class="item-hidden-tablet item-hidden-desktop">Поиск по сайту</span>
Тут речь даже не конкретно об иконке, а в самих классах. Я понимаю, ты создала два утилитарных класса и просто раскидываешь их в разметке там где нужно. Я не встречал такого способа, но думаю что он имеет право жить. Из плюсов - не надо писать лишние стили. Из минусов - разметка становится разбухшей. Не буду заворачивать, но я не встречал пока такого подхода.

2022-04-11 10:43 UTC, summertime-fms commented on source/form.html
> +                        <span class="nav-value">пока пуста</span>
Вынести в спан. Но класс то нужен чтобы составить селектор, а в селекторе тут нет смысла.

2022-04-12 07:51 UTC, merged